name: CI workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml
    permissions: write-all

  commitlint:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wagoid/commitlint-github-action@v6

  angular-build:
    uses: ./.github/workflows/angular-build.yml
    permissions: write-all
